#!/bin/sh

tmux new-session -d -s Session

# Some window definitions
tmux new-window -t Session:1 -n "Chat"
tmux new-window -t Session:2 -n "SSH"
tmux new-window -t Session:3 -n "SSH"
tmux new-window -t Session:4 -n "Shell"
tmux new-window -t Session:5 -n "Shell"
tmux new-window -t Session:6 -n "Shell"

# select and attach
tmux select-window -t Session:1
tmux -2 attach-session -t Session
