#!/bin/sh

tmux new-session -d -s Session -n "Chat"

# Some window definitions
tmux new-window -t Session:2 -n "SSH"
tmux new-window -t Session:3 -n "Shell"
tmux new-window -t Session:4 -n "SSH"
tmux new-window -t Session:5 -n "Shell"
tmux new-window -t Session:6 -n "SSH"
tmux new-window -t Session:7 -n "Shell"
tmux new-window -t Session:8 -n "Mail"
tmux new-window -t Session:9 -n "Edits"

# select and attach
tmux select-window -t Session:1
tmux -2 attach-session -t Session
