#!/bin/sh

tmux new-session -d -s Secondary -n "SSH"

# Some window definitions
tmux new-window -t Secondary:2 -n "SSH"
tmux new-window -t Secondary:3 -n "SSH"
tmux new-window -t Secondary:4 -n "Shell"
tmux new-window -t Secondary:5 -n "Shell"
tmux new-window -t Secondary:6 -n "Shell"
tmux new-window -t Secondary:7 -n "Shell"
tmux new-window -t Secondary:8 -n "Misc"

# select and attach
tmux select-window -t Secondary:1
tmux -2 attach-session -t Secondary
