#################################################################################
# FILE: ~/.bash_profile
# AUTHOR: Collin "Ridayah" O'Connor <ridayah@gmail.com>
# VERSION: 1.0.1
# This really is to simply let our .bashrc contain all functions.  Everything
# important is gonna be there.  Executed by login shells.
#################################################################################

# include .bashrc if it exists
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
export PATH="/usr/local/sbin:$PATH"
